
services:

  # Building and testing environment
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: portainer/portainer:latest
    container_name: portainer
    stdin_open: true
    tty: true
    command: ["/bin/zsh"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    network_mode: "host"
